"""Add speaker diarization fields to Transcription model

Revision ID: 23c2645ff2d8
Revises: c4d5e6f7g8h9
Create Date: 2025-11-10 20:13:40.046259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c2645ff2d8'
down_revision = 'c4d5e6f7g8h9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_diarization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('speakers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('diarization_segments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription', schema=None) as batch_op:
        batch_op.drop_column('diarization_segments')
        batch_op.drop_column('speakers_count')
        batch_op.drop_column('has_diarization')

    # ### end Alembic commands ###
